name: Build and upload rootfs image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download vmlinux
        uses: robinraju/release-downloader@v1
        with:
          # repository: memory-meld/clearlinux-images
          tag: v0.0.1
          fileName: vmlinux
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Prepare dependencies
        run: |
          # cloudhypervisor
          wget --quiet https://github.com/cloud-hypervisor/cloud-hypervisor/releases/latest/download/cloud-hypervisor
          chmod a+x cloud-hypervisor
          wget --quiet https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-x86_64-unknown-linux-musl.tar.gz
          tar --strip-components=1 -axvf fd-v10.1.0-x86_64-unknown-linux-musl.tar.gz fd-v10.1.0-x86_64-unknown-linux-musl/fd
          sudo apt update
          sudo apt install -y libvirt-daemon-system libvirt-clients qemu-utils coreutils iproute2 curl wget fd-find jq xz-utils dosfstools mtools uuid-runtime fdisk gdisk parted e2fsprogs util-linux bridge-utils
          sudo systemctl --no-pager --full start libvirtd
          sudo adduser $USER libvirt
          sudo chmod a+rw /dev/kvm

      # Runs a set of commands using the runners shell
      - name: Build and compress
        run: |
          export PATH="$PWD:$PATH"
          bash build.sh
          zstd -T0 root.img

      - uses: actions/upload-artifact@v3
        with:
          name: stdout
          path: stdout

      - uses: actions/upload-artifact@v3
        with:
          name: stderr
          path: stderr

      - uses: actions/upload-artifact@v3
        with:
          name: journalctl.log
          path: journalctl.log

      - uses: actions/upload-artifact@v3
        with:
          name: root.img.zst
          path: root.img.zst
