name: Build and upload rootfs image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Every Saturday 18:05 UTC
    - cron: "5 18 * * 6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-24.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - uses: actions/checkout@v4

      - name: Download vmlinux.bin
        uses: robinraju/release-downloader@v1
        with:
          tag: v0.0.1
          fileName: vmlinux.bin

      - name: Prepare dependencies
        run: |
          sudo apt update
          sudo apt install -y libvirt-daemon-system libvirt-clients qemu-utils coreutils iproute2 curl wget xz-utils dosfstools mtools uuid-runtime fdisk gdisk parted e2fsprogs util-linux bridge-utils jq
          sudo systemctl --no-pager --full start libvirtd
          sudo adduser $USER libvirt
          sudo chmod a+rw /dev/kvm

      - name: Build
        run: |
          export PATH="$PWD/bin:$PATH"
          bash build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: log
          path: |
            stdout
            stderr
            journalctl.log

      - name: Prepare image to upload
        run: |
          zstd -T0 root.img

      - uses: actions/upload-artifact@v4
        with:
          name: root.img.zst
          path: root.img.zst
