# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: clear

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download vmlinux
        uses: blauqs/actions-download-asset@v1.2
        with:
          repo: vtta/clearlinux-images
          version: 0.0.1
          file: vmlinux
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Prepare dependencies
        run: |
          # cloudhypervisor
          wget https://github.com/cloud-hypervisor/cloud-hypervisor/releases/latest/download/cloud-hypervisor
          chmod a+x cloud-hypervisor

      # Runs a set of commands using the runners shell
      - name: Build and compress
        run: |
          export PATH="$PWD:$PATH"
          bash build.sh
          zstd root.img
      - uses: actions/upload-artifact@v3
        with:
          name: final image
          path: root.img.zst
