name: Build and upload rootfs image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Every Saturday 18:05 UTC
    - cron: "5 18 * * 6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-24.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - uses: actions/checkout@v4

      - name: Download vmlinux.bin
        uses: robinraju/release-downloader@v1
        with:
          # repository: memory-meld/clearlinux-images
          tag: v0.0.1
          fileName: vmlinux.bin
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare dependencies
        run: |
          sudo apt update
          sudo apt install -y libvirt-daemon-system libvirt-clients qemu-utils coreutils iproute2 curl wget xz-utils dosfstools mtools uuid-runtime fdisk gdisk parted e2fsprogs util-linux bridge-utils jq
          sudo systemctl --no-pager --full start libvirtd
          sudo adduser $USER libvirt
          sudo chmod a+rw /dev/kvm

      - name: Build and compress
        run: |
          export PATH="$PWD/bin:$PATH"
          bash build.sh
          zstd -T0 root.img

      - name: Upload continuous assets
        if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            root.img.zst
            stdout
            stderr
            journalctl.log
          prerelease: true
          draft: false
          tag_name: continuous
          name: Continuous build
          append_body: true

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            root.img.zst
            stdout
            stderr
            journalctl.log
          name: Release build
          append_body: true
